/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controller

import (
	"context"
	"strings"
	"time"

	"github.com/go-logr/logr"
	pkgerrors "github.com/pkg/errors"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/klog/v2"
	"sigs.k8s.io/controller-runtime/pkg/client"
	"sigs.k8s.io/controller-runtime/pkg/client/apiutil"
	"sigs.k8s.io/controller-runtime/pkg/controller"
	"sigs.k8s.io/controller-runtime/pkg/handler"
	"sigs.k8s.io/controller-runtime/pkg/predicate"
	"sigs.k8s.io/controller-runtime/pkg/reconcile"

	mcbuilder "sigs.k8s.io/multicluster-runtime/pkg/builder"
	mccontext "sigs.k8s.io/multicluster-runtime/pkg/context"
	mchandler "sigs.k8s.io/multicluster-runtime/pkg/handler"
	mcmanager "sigs.k8s.io/multicluster-runtime/pkg/manager"
	mcreconcile "sigs.k8s.io/multicluster-runtime/pkg/reconcile"

	"sigs.k8s.io/cluster-api/feature"
	"sigs.k8s.io/cluster-api/util/cache"
	predicatesutil "sigs.k8s.io/cluster-api/util/predicates"
)

// MulticlusterBuilder builds one controller that serves every cluster a
// multicluster-runtime provider offers, rather than one controller per cluster.
//
// # What it is for
//
// Running Cluster API against a provider that exposes many logical clusters —
// kcp workspaces, or any other multicluster-runtime provider — currently means
// instantiating the whole controller set once per cluster, because
// SetupWithManager builds a controller bound to one manager and keyed on
// reconcile.Request, which carries no cluster. The per-cluster cost of that is
// a controller, a workqueue, an eagerly-started worker pool and an
// event-handler registration per watch, for every cluster.
//
// This builder produces a single controller keyed on mcreconcile.Request, which
// does carry the cluster, so those costs are paid once for the fleet.
//
// # What it deliberately does not change
//
// The reconciler. A reconciler written against reconcile.Request is passed
// through unmodified: Build adapts it with
// mccontext.ReconcilerWithClusterInContext, which puts the cluster in the
// context and calls Reconcile with the plain request. Reconcile bodies, and the
// map functions passed to Watches, are untouched — which is the whole point,
// because that is where a controller's behaviour lives.
//
// # Parity with Builder
//
// Everything Builder does around the reconciler — the reconcile cache, the
// exponential rate limiter, the metrics, the reconciliation timeout, the log
// constructor — is shared with this builder rather than reimplemented, via the
// generic reconcilerWrapper and controllerWrapper. A second copy would drift,
// and drift in rate limiting or deferral is a behaviour change nobody sees.
type MulticlusterBuilder struct {
	builder           *mcbuilder.TypedBuilder[mcreconcile.Request]
	mgr               mcmanager.Manager
	predicateLog      logr.Logger
	options           controller.TypedOptions[mcreconcile.Request]
	forObject         client.Object
	controllerName    string
	rateLimitInterval time.Duration
}

// NewMulticlusterControllerManagedBy returns a builder for a controller that
// serves every cluster the manager's provider offers.
func NewMulticlusterControllerManagedBy(m mcmanager.Manager, predicateLog logr.Logger) *MulticlusterBuilder {
	return &MulticlusterBuilder{
		builder:      mcbuilder.TypedControllerManagedBy[mcreconcile.Request](m),
		mgr:          m,
		predicateLog: predicateLog,
	}
}

// For defines the type of Object being reconciled.
func (blder *MulticlusterBuilder) For(object client.Object, opts ...mcbuilder.ForOption) *MulticlusterBuilder {
	blder.forObject = object
	blder.builder.For(object, opts...)
	return blder
}

// Owns defines types of Objects being generated by the controller.
func (blder *MulticlusterBuilder) Owns(object client.Object, predicates ...predicate.Predicate) *MulticlusterBuilder {
	// Note: Prepend a ResourceIsChanged predicate to all "secondary" watches, matching Builder.
	predicates = append([]predicate.Predicate{predicatesutil.ResourceIsChanged(blder.mgr.GetLocalManager().GetScheme(), blder.predicateLog)}, predicates...)
	blder.builder.Owns(object, mcbuilder.WithPredicates(predicates...))
	return blder
}

// Watches defines the type of Object to watch, and the handler to enqueue with.
//
// The handler is an ordinary single-cluster handler — exactly what the
// reconcilers already construct — and is lifted here rather than at the call
// site. mchandler.TypedLift wraps it so the requests it enqueues carry the
// cluster the event came from, which is what keeps two clusters' identically
// named objects apart in the queue.
//
// That is what allows a reconciler's existing map functions to be reused
// verbatim: they still produce plain reconcile.Requests, and the lift attaches
// the cluster around them.
func (blder *MulticlusterBuilder) Watches(object client.Object, eventHandler handler.TypedEventHandler[client.Object, reconcile.Request], predicates ...predicate.Predicate) *MulticlusterBuilder {
	predicates = append([]predicate.Predicate{predicatesutil.ResourceIsChanged(blder.mgr.GetLocalManager().GetScheme(), blder.predicateLog)}, predicates...)
	blder.builder.Watches(object, mchandler.TypedLift(eventHandler), mcbuilder.WithPredicates(predicates...))
	return blder
}

// WithOptions overrides the controller options. Defaults to empty.
func (blder *MulticlusterBuilder) WithOptions(options controller.TypedOptions[mcreconcile.Request]) *MulticlusterBuilder {
	blder.options = options
	return blder
}

// WithRateLimitInterval sets the minimum interval between two reconciles of the
// same object.
func (blder *MulticlusterBuilder) WithRateLimitInterval(interval time.Duration) *MulticlusterBuilder {
	blder.rateLimitInterval = interval
	return blder
}

// WithEventFilter sets a predicate applied to all watches.
func (blder *MulticlusterBuilder) WithEventFilter(p predicate.Predicate) *MulticlusterBuilder {
	blder.builder.WithEventFilter(p)
	return blder
}

// Named sets the controller name. Defaults to the lowercased kind of the For
// object.
func (blder *MulticlusterBuilder) Named(name string) *MulticlusterBuilder {
	blder.controllerName = name
	blder.builder.Named(name)
	return blder
}

// Complete builds the controller.
func (blder *MulticlusterBuilder) Complete(ctx context.Context, r reconcile.Reconciler) error {
	_, err := blder.Build(ctx, r)
	return err
}

// Build builds the controller and returns it.
//
// The reconciler is an ordinary single-cluster reconcile.Reconciler. It is
// adapted, not rewritten: ReconcilerWithClusterInContext unwraps the
// multicluster request, puts its cluster in the context, and calls Reconcile
// with the plain request the reconciler already expects.
func (blder *MulticlusterBuilder) Build(ctx context.Context, r reconcile.Reconciler) (ControllerFor[mcreconcile.Request], error) {
	if feature.Gates.Enabled(feature.ReconcilerRateLimiting) && !feature.Gates.Enabled(feature.PriorityQueue) {
		return nil, pkgerrors.New("if feature gate ReconcilerRateLimiting is enabled, feature gate PriorityQueue must be enabled as well")
	}

	localMgr := blder.mgr.GetLocalManager()

	// Get GVK of the for object.
	var gvk schema.GroupVersionKind
	hasGVK := blder.forObject != nil
	if hasGVK {
		var err error
		gvk, err = apiutil.GVKForObject(blder.forObject, localMgr.GetScheme())
		if err != nil {
			return nil, err
		}
	}

	controllerName := blder.controllerName
	if controllerName == "" {
		controllerName = strings.ToLower(gvk.Kind)
	}

	if blder.options.ReconciliationTimeout == 0 {
		blder.options.ReconciliationTimeout = defaultReconciliationTimeout
	}

	if blder.options.LogConstructor == nil {
		log := localMgr.GetLogger().WithValues("controller", controllerName)
		if hasGVK {
			log = log.WithValues("controllerGroup", gvk.Group, "controllerKind", gvk.Kind)
		}

		blder.options.LogConstructor = func(req *mcreconcile.Request) logr.Logger {
			log := log
			if req != nil {
				// The cluster is logged as well as the object, because in a
				// fleet-wide controller the object name alone does not identify
				// what was reconciled.
				log = log.WithValues("cluster", req.ClusterName)
				if hasGVK {
					log = log.WithValues(gvk.Kind, klog.KRef(req.Namespace, req.Name))
				}
			}
			return log
		}
	}

	rateLimitInterval := time.Second
	if blder.rateLimitInterval > time.Second {
		rateLimitInterval = blder.rateLimitInterval
	}

	var queueRateLimiter *typedItemExponentialFailureRateLimiter[mcreconcile.Request]
	if feature.Gates.Enabled(feature.ReconcilerRateLimiting) {
		queueRateLimiter = newTypedItemExponentialFailureRateLimiter[mcreconcile.Request](rateLimitInterval, 5*time.Millisecond, 1000*time.Second)
		blder.options.RateLimiter = queueRateLimiter
	}

	blder.builder.WithOptions(blder.options)

	reconcileCache := cache.New[reconcileCacheEntry[mcreconcile.Request]](ctx, cache.DefaultTTL)

	// The consistency store is the local manager's.
	//
	// Correct only while no converted controller uses it: its writes are keyed
	// by namespace and name with no cluster, so a fleet-wide controller that
	// recorded writes would let one cluster's deferral apply to another's
	// reconcile. The controllers converted first — cluster and machine — never
	// call WroteAt, and EnsureReady on an owner it has no record of returns
	// nothing, so the store stays empty and inert.
	//
	// Converting machineset or machinedeployment, which do call it, MUST make
	// this cluster-aware first.
	consistencyStore := newConsistencyStore(localMgr.GetScheme(), localMgr.GetCache())

	c, err := blder.builder.Build(&reconcilerWrapper[mcreconcile.Request]{
		name:              controllerName,
		reconciler:        mccontext.ReconcilerWithClusterInContext(r),
		reconcileCache:    reconcileCache,
		rateLimitInterval: rateLimitInterval,
		queueRateLimiter:  queueRateLimiter,
		consistencyStore:  consistencyStore,
		// The embedded request is the object identity; the cluster is carried
		// alongside it and is deliberately not part of what the consistency
		// store sees, per the note above.
		namespacedName: func(req mcreconcile.Request) types.NamespacedName { return req.NamespacedName },
	})
	if err != nil {
		return nil, err
	}

	reconcileTotal.WithLabelValues(controllerName, labelError).Add(0)
	reconcileTotal.WithLabelValues(controllerName, labelRequeueAfter).Add(0)
	reconcileTotal.WithLabelValues(controllerName, labelRequeue).Add(0)
	reconcileTotal.WithLabelValues(controllerName, labelSuccess).Add(0)

	return &controllerWrapper[mcreconcile.Request]{
		TypedController:  c,
		reconcileCache:   reconcileCache,
		consistencyStore: consistencyStore,
		// DeferNextReconcileForObject is called from inside Reconcile with only
		// an object, so there is no cluster to attach here. The resulting
		// request therefore defers the object in *every* cluster.
		//
		// Harmless for the controllers converted first, which never call it,
		// and a correctness hazard for any that do — recorded alongside the
		// consistency store constraint above.
		newRequest: func(nn types.NamespacedName) mcreconcile.Request {
			return mcreconcile.Request{Request: reconcile.Request{NamespacedName: nn}}
		},
	}, nil
}
